/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedObjecoesRouteImport } from './routes/_authenticated/objecoes'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObjecoesRoute = AuthenticatedObjecoesRouteImport.update({
  id: '/objecoes',
  path: '/objecoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/objecoes': typeof AuthenticatedObjecoesRoute
  '/servicos': typeof AuthenticatedServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/objecoes': typeof AuthenticatedObjecoesRoute
  '/servicos': typeof AuthenticatedServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/objecoes': typeof AuthenticatedObjecoesRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/atividades'
    | '/clientes'
    | '/empresas'
    | '/leads'
    | '/objecoes'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/atividades'
    | '/clientes'
    | '/empresas'
    | '/leads'
    | '/objecoes'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/atividades'
    | '/_authenticated/clientes'
    | '/_authenticated/empresas'
    | '/_authenticated/leads'
    | '/_authenticated/objecoes'
    | '/_authenticated/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/objecoes': {
      id: '/_authenticated/objecoes'
      path: '/objecoes'
      fullPath: '/objecoes'
      preLoaderRoute: typeof AuthenticatedObjecoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedObjecoesRoute: typeof AuthenticatedObjecoesRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedObjecoesRoute: AuthenticatedObjecoesRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
