/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAfiliadosRouteImport } from './routes/_authenticated/afiliados'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCombosRouteImport } from './routes/_authenticated/combos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedFollowupRouteImport } from './routes/_authenticated/followup'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedNichosRouteImport } from './routes/_authenticated/nichos'
import { Route as AuthenticatedObjecoesRouteImport } from './routes/_authenticated/objecoes'
import { Route as AuthenticatedPesquisaRouteImport } from './routes/_authenticated/pesquisa'
import { Route as AuthenticatedPrecificacaoRouteImport } from './routes/_authenticated/precificacao'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedPropostasRouteImport } from './routes/_authenticated/propostas'
import { Route as AuthenticatedRecibosRouteImport } from './routes/_authenticated/recibos'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as ApiMarketResearchRouteImport } from './routes/api/market-research'
import { Route as ApiNicheAiRouteImport } from './routes/api/niche-ai'
import { Route as ApiPlacesRouteImport } from './routes/api/places'
import { Route as ApiProposalAiRouteImport } from './routes/api/proposal-ai'
import { Route as ApiSendProposalRouteImport } from './routes/api/send-proposal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAfiliadosRoute = AuthenticatedAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCombosRoute = AuthenticatedCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupRoute = AuthenticatedFollowupRouteImport.update({
  id: '/followup',
  path: '/followup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNichosRoute = AuthenticatedNichosRouteImport.update({
  id: '/nichos',
  path: '/nichos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObjecoesRoute = AuthenticatedObjecoesRouteImport.update({
  id: '/objecoes',
  path: '/objecoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesquisaRoute = AuthenticatedPesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecificacaoRoute =
  AuthenticatedPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropostasRoute = AuthenticatedPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecibosRoute = AuthenticatedRecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiMarketResearchRoute = ApiMarketResearchRouteImport.update({
  id: '/api/market-research',
  path: '/api/market-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNicheAiRoute = ApiNicheAiRouteImport.update({
  id: '/api/niche-ai',
  path: '/api/niche-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesRoute = ApiPlacesRouteImport.update({
  id: '/api/places',
  path: '/api/places',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProposalAiRoute = ApiProposalAiRouteImport.update({
  id: '/api/proposal-ai',
  path: '/api/proposal-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendProposalRoute = ApiSendProposalRouteImport.update({
  id: '/api/send-proposal',
  path: '/api/send-proposal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/afiliados': typeof AuthenticatedAfiliadosRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/combos': typeof AuthenticatedCombosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/followup': typeof AuthenticatedFollowupRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/nichos': typeof AuthenticatedNichosRoute
  '/objecoes': typeof AuthenticatedObjecoesRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/recibos': typeof AuthenticatedRecibosRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/api/market-research': typeof ApiMarketResearchRoute
  '/api/niche-ai': typeof ApiNicheAiRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/proposal-ai': typeof ApiProposalAiRoute
  '/api/send-proposal': typeof ApiSendProposalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/afiliados': typeof AuthenticatedAfiliadosRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/combos': typeof AuthenticatedCombosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/followup': typeof AuthenticatedFollowupRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/nichos': typeof AuthenticatedNichosRoute
  '/objecoes': typeof AuthenticatedObjecoesRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/recibos': typeof AuthenticatedRecibosRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/api/market-research': typeof ApiMarketResearchRoute
  '/api/niche-ai': typeof ApiNicheAiRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/proposal-ai': typeof ApiProposalAiRoute
  '/api/send-proposal': typeof ApiSendProposalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/afiliados': typeof AuthenticatedAfiliadosRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/combos': typeof AuthenticatedCombosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/followup': typeof AuthenticatedFollowupRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/nichos': typeof AuthenticatedNichosRoute
  '/_authenticated/objecoes': typeof AuthenticatedObjecoesRoute
  '/_authenticated/pesquisa': typeof AuthenticatedPesquisaRoute
  '/_authenticated/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/propostas': typeof AuthenticatedPropostasRoute
  '/_authenticated/recibos': typeof AuthenticatedRecibosRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/api/market-research': typeof ApiMarketResearchRoute
  '/api/niche-ai': typeof ApiNicheAiRoute
  '/api/places': typeof ApiPlacesRoute
  '/api/proposal-ai': typeof ApiProposalAiRoute
  '/api/send-proposal': typeof ApiSendProposalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/afiliados'
    | '/assistente'
    | '/atividades'
    | '/clientes'
    | '/combos'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/followup'
    | '/leads'
    | '/nichos'
    | '/objecoes'
    | '/pesquisa'
    | '/precificacao'
    | '/prompts'
    | '/propostas'
    | '/recibos'
    | '/servicos'
    | '/api/market-research'
    | '/api/niche-ai'
    | '/api/places'
    | '/api/proposal-ai'
    | '/api/send-proposal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/afiliados'
    | '/assistente'
    | '/atividades'
    | '/clientes'
    | '/combos'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/followup'
    | '/leads'
    | '/nichos'
    | '/objecoes'
    | '/pesquisa'
    | '/precificacao'
    | '/prompts'
    | '/propostas'
    | '/recibos'
    | '/servicos'
    | '/api/market-research'
    | '/api/niche-ai'
    | '/api/places'
    | '/api/proposal-ai'
    | '/api/send-proposal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/afiliados'
    | '/_authenticated/assistente'
    | '/_authenticated/atividades'
    | '/_authenticated/clientes'
    | '/_authenticated/combos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/followup'
    | '/_authenticated/leads'
    | '/_authenticated/nichos'
    | '/_authenticated/objecoes'
    | '/_authenticated/pesquisa'
    | '/_authenticated/precificacao'
    | '/_authenticated/prompts'
    | '/_authenticated/propostas'
    | '/_authenticated/recibos'
    | '/_authenticated/servicos'
    | '/api/market-research'
    | '/api/niche-ai'
    | '/api/places'
    | '/api/proposal-ai'
    | '/api/send-proposal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiMarketResearchRoute: typeof ApiMarketResearchRoute
  ApiNicheAiRoute: typeof ApiNicheAiRoute
  ApiPlacesRoute: typeof ApiPlacesRoute
  ApiProposalAiRoute: typeof ApiProposalAiRoute
  ApiSendProposalRoute: typeof ApiSendProposalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/afiliados': {
      id: '/_authenticated/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AuthenticatedAfiliadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/combos': {
      id: '/_authenticated/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof AuthenticatedCombosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followup': {
      id: '/_authenticated/followup'
      path: '/followup'
      fullPath: '/followup'
      preLoaderRoute: typeof AuthenticatedFollowupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nichos': {
      id: '/_authenticated/nichos'
      path: '/nichos'
      fullPath: '/nichos'
      preLoaderRoute: typeof AuthenticatedNichosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/objecoes': {
      id: '/_authenticated/objecoes'
      path: '/objecoes'
      fullPath: '/objecoes'
      preLoaderRoute: typeof AuthenticatedObjecoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesquisa': {
      id: '/_authenticated/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof AuthenticatedPesquisaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precificacao': {
      id: '/_authenticated/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof AuthenticatedPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/propostas': {
      id: '/_authenticated/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AuthenticatedPropostasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recibos': {
      id: '/_authenticated/recibos'
      path: '/recibos'
      fullPath: '/recibos'
      preLoaderRoute: typeof AuthenticatedRecibosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/market-research': {
      id: '/api/market-research'
      path: '/api/market-research'
      fullPath: '/api/market-research'
      preLoaderRoute: typeof ApiMarketResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/niche-ai': {
      id: '/api/niche-ai'
      path: '/api/niche-ai'
      fullPath: '/api/niche-ai'
      preLoaderRoute: typeof ApiNicheAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places': {
      id: '/api/places'
      path: '/api/places'
      fullPath: '/api/places'
      preLoaderRoute: typeof ApiPlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proposal-ai': {
      id: '/api/proposal-ai'
      path: '/api/proposal-ai'
      fullPath: '/api/proposal-ai'
      preLoaderRoute: typeof ApiProposalAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-proposal': {
      id: '/api/send-proposal'
      path: '/api/send-proposal'
      fullPath: '/api/send-proposal'
      preLoaderRoute: typeof ApiSendProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAfiliadosRoute: typeof AuthenticatedAfiliadosRoute
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCombosRoute: typeof AuthenticatedCombosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedFollowupRoute: typeof AuthenticatedFollowupRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedNichosRoute: typeof AuthenticatedNichosRoute
  AuthenticatedObjecoesRoute: typeof AuthenticatedObjecoesRoute
  AuthenticatedPesquisaRoute: typeof AuthenticatedPesquisaRoute
  AuthenticatedPrecificacaoRoute: typeof AuthenticatedPrecificacaoRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedPropostasRoute: typeof AuthenticatedPropostasRoute
  AuthenticatedRecibosRoute: typeof AuthenticatedRecibosRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAfiliadosRoute: AuthenticatedAfiliadosRoute,
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCombosRoute: AuthenticatedCombosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedFollowupRoute: AuthenticatedFollowupRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedNichosRoute: AuthenticatedNichosRoute,
  AuthenticatedObjecoesRoute: AuthenticatedObjecoesRoute,
  AuthenticatedPesquisaRoute: AuthenticatedPesquisaRoute,
  AuthenticatedPrecificacaoRoute: AuthenticatedPrecificacaoRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedPropostasRoute: AuthenticatedPropostasRoute,
  AuthenticatedRecibosRoute: AuthenticatedRecibosRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiMarketResearchRoute: ApiMarketResearchRoute,
  ApiNicheAiRoute: ApiNicheAiRoute,
  ApiPlacesRoute: ApiPlacesRoute,
  ApiProposalAiRoute: ApiProposalAiRoute,
  ApiSendProposalRoute: ApiSendProposalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
